spring.application.name=backend-api

# Conexión a MySQL para Mi AgroTienda
spring.datasource.url=jdbc:mysql://localhost:3306/mi_agrotienda_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=admin

# Configuración de JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

app.jwt.secret=change-me-in-prod-change-me-in-prod-change-me-in-prod
app.jwt.expiration-ms=86400000
